version: "3.3"
services:
   rethinkdb:
      image: rethinkdb:2.3.6
      ports:
         - "8080:8080"
         - "28015:28015"
   seed:
      image: ${REGISTRY_HOST}/${REGISTRY_NAMESPACE}/seed
      build:
         context: ./services/seed
      restart: "no"
      depends_on:
         - rethinkdb
   controller:
      image: ${REGISTRY_HOST}/${REGISTRY_NAMESPACE}/mvp-controller
      build:
         dockerfile: Dockerfile
         context: ./services/controller
      restart: "always"
      ports:
         - "80:80"
      depends_on:
         - seed
      environment:
         - "LOG_LEVEL=trace"
   resolver-api-domain-query-load:
      image: ${REGISTRY_HOST}/${REGISTRY_NAMESPACE}/mvp-microservice:api.domain.query.load
      build:
         context: ./services/resolvers/api/domain/query/load
      restart: "always"
   resolver-utils-get:
      image: ${REGISTRY_HOST}/${REGISTRY_NAMESPACE}/mvp-resolver:utils.get
      build:
         context: ./services/resolvers/utils/get
      restart: "always"
   view-ui-default:
      image: ${REGISTRY_HOST}/${REGISTRY_NAMESPACE}/mvp-ui
      build:
         context: ./services/ui
      restart: "always"
      environment:
         - "LOG_LEVEL=trace"
   view-api-default:
      image: ${REGISTRY_HOST}/${REGISTRY_NAMESPACE}/mvp-api
      build:
         context: ./services/api
      restart: "always"
      environment:
         - "LOG_LEVEL=trace"
